### ISSUE TITLE
Facer Game Design Document

### ISSUE THREAD

**Issue by isaacjgonzalez** [juanlod/DXPP#1]
Facer un pequeno documento en markdown.

**Comment by AlbertoGarciaMiguelez** [comment]
Q vengo del finde, así no hay quien se relaje tranquilo.

**Comment by 9RACHA** [comment]
Encantado de participar en este proyecto!

**Comment by isaacjgonzalez** [comment]
Gracias polo feedback, tereino en conta. Ánimo coa tarefa!
